# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

# Install dependencies (ignore prepare scripts to speed up build if necessary)
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build the project
RUN npm run build

# Expose port if necessary (optional)
# EXPOSE 3000

# Command to run the MCP server
CMD ["node", "dist/index.js"]
